# Generated by Django 6.0.8 on 2026-09-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('melee', 'Melee weapon'), ('firearm', 'Firearm'), ('bow', 'Bow'), ('crossbow', 'Crossbow'), ('armor', 'Armor'), ('deflection', 'Deflection item / shield'), ('ammo', 'Ammunition'), ('gear', 'Gear'), ('animal', 'Animal'), ('vehicle', 'Vehicle')], default='gear', max_length=20)),
                ('size', models.CharField(blank=True, choices=[('', '–'), ('minimal', 'Minimal (armor)'), ('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy'), ('super-heavy', 'Super-Heavy')], max_length=20)),
                ('variants', models.JSONField(blank=True, default=list)),
                ('material', models.CharField(choices=[('metal', 'Metal'), ('wood', 'Wood'), ('organic', 'Organic'), ('textile', 'Textile')], default='metal', max_length=20)),
                ('beta', models.BooleanField(default=False, help_text='Beta item: +2 augment slots')),
                ('concealable', models.BooleanField(default=False)),
                ('ap_use', models.IntegerField(blank=True, null=True)),
                ('ap_ready', models.IntegerField(blank=True, null=True)),
                ('dc', models.IntegerField(blank=True, null=True, verbose_name='damage class')),
                ('reach', models.IntegerField(blank=True, help_text='ft (melee)', null=True)),
                ('range', models.IntegerField(blank=True, help_text='base range in ft', null=True)),
                ('increment', models.IntegerField(blank=True, help_text='range increment in ft', null=True)),
                ('soak', models.IntegerField(blank=True, null=True, verbose_name='soak class')),
                ('eva_penalty', models.IntegerField(blank=True, null=True)),
                ('spd_penalty', models.IntegerField(blank=True, null=True)),
                ('climb_swim_penalty', models.IntegerField(blank=True, null=True)),
                ('deflect_bonus', models.IntegerField(blank=True, null=True)),
                ('deflect_ranged', models.BooleanField(default=False)),
                ('deflect_melee', models.BooleanField(default=True)),
                ('augments', models.JSONField(blank=True, default=list, help_text='[["augment-slug", marque], ...]')),
                ('modifiers', models.JSONField(blank=True, default=list)),
                ('price_dukes', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_starting_gear', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('book', 'Playing Guide'), ('custom', 'Custom')], default='custom', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'kind'), name='unique_template_name_kind')],
            },
        ),
    ]
