# Generated by Django 6.0.8 on 2026-09-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_hands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtemplate',
            name='hands',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'No hand (worn)'), (1, 'One-handed'), (2, 'Two-handed')], help_text='empty = size table (melee/firearm/crossbow: light & medium one-handed; bows always two-handed; cloak no hand, shield/parrying dagger one hand)', null=True),
        ),
    ]
