# Generated by Django 6.0.8 on 2026-09-26 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('player_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'In creation'), ('active', 'Active')], default='draft', max_length=10)),
                ('wizard_step', models.PositiveSmallIntegerField(default=1)),
                ('target_level', models.PositiveSmallIntegerField(default=1)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('race', models.CharField(blank=True, max_length=40)),
                ('nationality', models.CharField(blank=True, max_length=40)),
                ('nationality_custom', models.CharField(blank=True, max_length=80)),
                ('religion', models.CharField(blank=True, max_length=80)),
                ('age', models.CharField(blank=True, max_length=30)),
                ('height', models.CharField(blank=True, max_length=30)),
                ('weight', models.CharField(blank=True, max_length=30)),
                ('personality', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('xp', models.PositiveSmallIntegerField(default=0)),
                ('current_hp', models.IntegerField(blank=True, null=True)),
                ('current_wounds', models.IntegerField(blank=True, null=True)),
                ('money_on_hand', models.IntegerField(default=0, help_text='in dukes')),
                ('money_in_bank', models.IntegerField(default=0, help_text='in dukes')),
                ('fixed_traits', models.JSONField(blank=True, default=list)),
                ('random_traits', models.JSONField(blank=True, default=list)),
                ('trait_rolls', models.JSONField(blank=True, default=list)),
                ('trait_choices', models.JSONField(blank=True, default=dict)),
                ('skills', models.JSONField(blank=True, default=dict)),
                ('specialties', models.JSONField(blank=True, default=list, help_text='[["slug", level], ...]')),
                ('augments', models.JSONField(blank=True, default=list)),
                ('body_augments', models.JSONField(blank=True, default=list, help_text='[["slug", marque], ...]')),
                ('stories', models.JSONField(blank=True, default=list)),
                ('stance', models.CharField(blank=True, max_length=120)),
                ('toggles', models.JSONField(blank=True, default=list)),
                ('misc', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='NarratorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_choose_random_trait', models.BooleanField(default=False, help_text='Players may pick their random racial trait instead of rolling')),
                ('allow_reroll_random_trait', models.BooleanField(default=True, help_text='Players may re-roll the racial trait')),
                ('background_story_count', models.PositiveSmallIntegerField(default=1)),
                ('max_starting_level', models.PositiveSmallIntegerField(default=1)),
                ('allow_player_admin_mode', models.BooleanField(default=True, help_text='Players who unlocked a character may use admin mode on it')),
            ],
            options={
                'verbose_name_plural': 'narrator settings',
            },
        ),
        migrations.CreateModel(
            name='CustomModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text="e.g. 'Story: Burn Victim'", max_length=120)),
                ('stat', models.CharField(choices=[('acc', 'ACC'), ('eva', 'EVA'), ('stk', 'STK'), ('def', 'DEF'), ('pri', 'PRI'), ('spd', 'SPD'), ('swim', 'SWIM'), ('climb', 'CLIMB'), ('fly', 'FLY'), ('aug', 'AUG'), ('diy', 'DIY'), ('wnd', 'WND'), ('hp', 'HP'), ('soak', 'SOAK'), ('dc', 'DC'), ('skill:Brawl', 'Skill: Brawl'), ('skill:Frenzy', 'Skill: Frenzy'), ('skill:Overpower', 'Skill: Overpower'), ('skill:Resilience', 'Skill: Resilience'), ('skill:Espionage', 'Skill: Espionage'), ('skill:Expertise', 'Skill: Expertise'), ('skill:Showmanship', 'Skill: Showmanship'), ('skill:Tactical', 'Skill: Tactical'), ('skill:Ace', 'Skill: Ace'), ('skill:Agility', 'Skill: Agility'), ('skill:Marksmanship', 'Skill: Marksmanship'), ('skill:Swashbuckling', 'Skill: Swashbuckling'), ('skill:Faith', 'Skill: Faith'), ('skill:Grace', 'Skill: Grace'), ('skill:Luck', 'Skill: Luck'), ('skill:Shamanism', 'Skill: Shamanism'), ('skill:Alchemy', 'Skill: Alchemy'), ('skill:Armsmith', 'Skill: Armsmith'), ('skill:Automata', 'Skill: Automata'), ('skill:Bio-Flux', 'Skill: Bio-Flux'), ('skill:Engineer', 'Skill: Engineer'), ('skill:Gadgetry', 'Skill: Gadgetry'), ('attr:Brute', 'Attribute: Brute'), ('attr:Cunning', 'Attribute: Cunning'), ('attr:Dexterity', 'Attribute: Dexterity'), ('attr:Spirit', 'Attribute: Spirit'), ('attr:Sciences', 'Attribute: Sciences')], max_length=40)),
                ('value', models.IntegerField()),
                ('when', models.CharField(choices=[('always', 'Always'), ('toggle', 'Toggle on sheet')], default='always', max_length=10)),
                ('scope', models.CharField(choices=[('character', 'Character'), ('melee', 'Melee attacks'), ('ranged', 'Ranged attacks'), ('unarmed', 'Unarmed attacks')], default='character', max_length=12)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_modifiers', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='EffectEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('wound', 'Wound effect'), ('fatal', 'Fatal effect'), ('status', 'Status effect'), ('called', 'Called-shot effect')], max_length=10)),
                ('location', models.PositiveSmallIntegerField(blank=True, help_text='called-shot d12 location', null=True)),
                ('text', models.CharField(max_length=255)),
                ('lost_wounds', models.PositiveSmallIntegerField(default=0, help_text='permanent max-wound loss')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='characters.character')),
            ],
            options={
                'ordering': ['kind', 'created'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('melee', 'Melee weapon'), ('firearm', 'Firearm'), ('bow', 'Bow'), ('crossbow', 'Crossbow'), ('armor', 'Armor'), ('deflection', 'Deflection item / shield'), ('ammo', 'Ammunition'), ('gear', 'Gear'), ('animal', 'Animal'), ('vehicle', 'Vehicle')], default='gear', max_length=20)),
                ('size', models.CharField(blank=True, choices=[('', '–'), ('minimal', 'Minimal (armor)'), ('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy'), ('super-heavy', 'Super-Heavy')], max_length=20)),
                ('variants', models.JSONField(blank=True, default=list)),
                ('material', models.CharField(choices=[('metal', 'Metal'), ('wood', 'Wood'), ('organic', 'Organic'), ('textile', 'Textile')], default='metal', max_length=20)),
                ('beta', models.BooleanField(default=False, help_text='Beta item: +2 augment slots')),
                ('concealable', models.BooleanField(default=False)),
                ('ap_use', models.IntegerField(blank=True, null=True)),
                ('ap_ready', models.IntegerField(blank=True, null=True)),
                ('dc', models.IntegerField(blank=True, null=True, verbose_name='damage class')),
                ('reach', models.IntegerField(blank=True, help_text='ft (melee)', null=True)),
                ('range', models.IntegerField(blank=True, help_text='base range in ft', null=True)),
                ('increment', models.IntegerField(blank=True, help_text='range increment in ft', null=True)),
                ('soak', models.IntegerField(blank=True, null=True, verbose_name='soak class')),
                ('eva_penalty', models.IntegerField(blank=True, null=True)),
                ('spd_penalty', models.IntegerField(blank=True, null=True)),
                ('climb_swim_penalty', models.IntegerField(blank=True, null=True)),
                ('deflect_bonus', models.IntegerField(blank=True, null=True)),
                ('deflect_ranged', models.BooleanField(default=False)),
                ('deflect_melee', models.BooleanField(default=True)),
                ('augments', models.JSONField(blank=True, default=list, help_text='[["augment-slug", marque], ...]')),
                ('modifiers', models.JSONField(blank=True, default=list)),
                ('price_dukes', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('slot', models.CharField(choices=[('weapon1', 'Weapon 1'), ('weapon2', 'Weapon 2'), ('armor', 'Armor (worn)'), ('deflection', 'Deflection item'), ('worn', 'Worn / active'), ('carried', 'Carried'), ('stored', 'Stored')], default='carried', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='characters.character')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.itemtemplate')),
            ],
            options={
                'ordering': ['slot', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LevelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_logs', to='characters.character')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
