# Generated by Django 6.0.8 on 2026-09-26 10:44

from django.db import migrations, models


def link_existing(apps, schema_editor):
    """Old entries were free text: map known status names to keys, fold "called" into status."""
    from rules.engine import effects

    by_name = {e["name"].split(" (")[0].lower(): k for k, e in effects.EFFECTS.items() if e["kind"] == "status"}
    EffectEntry = apps.get_model("characters", "EffectEntry")
    for e in EffectEntry.objects.all():
        if e.kind == "called":
            e.kind = "status"
        if e.kind == "status" and not e.key:
            e.key = by_name.get(e.text.strip().lower(), "")
        e.save(update_fields=["kind", "key"])


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='effectentry',
            name='key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='effectentry',
            name='kind',
            field=models.CharField(choices=[('wound', 'Wound effect'), ('fatal', 'Fatal effect'), ('status', 'Status effect')], max_length=10),
        ),
        migrations.AlterField(
            model_name='effectentry',
            name='location',
            field=models.PositiveSmallIntegerField(blank=True, help_text='silhouette location 1-12', null=True),
        ),
        migrations.RunPython(link_existing, migrations.RunPython.noop),
    ]
