# Generated by Django 6.0.8 on 2026-09-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_effect_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='hands',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'One-handed'), (2, 'Two-handed')], help_text='empty = size table (melee/firearm/crossbow: light & medium one-handed; bows always two-handed)', null=True),
        ),
    ]
