# Generated by Django 6.0.8 on 2026-09-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_item_hands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='slot',
            field=models.CharField(choices=[('weapon1', 'Left hand'), ('weapon2', 'Right hand'), ('armor', 'Armor (worn)'), ('deflection', 'Deflection item'), ('worn', 'Worn / active'), ('carried', 'Carried'), ('stored', 'Stored')], default='carried', max_length=20),
        ),
    ]
