# Generated by Django 6.0.8 on 2026-09-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_hand_slot_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='specialty_choices',
            field=models.JSONField(blank=True, default=dict, help_text='choices made when learning, e.g. {"<battle-theme slug>": "singing"}'),
        ),
    ]
