# Generated by Django 6.0.8 on 2026-09-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_specialty_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effectentry',
            name='kind',
            field=models.CharField(choices=[('normal', 'Called-shot effect'), ('wound', 'Wound effect'), ('fatal', 'Fatal effect'), ('status', 'Status effect')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='hands',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'No hand (worn)'), (1, 'One-handed'), (2, 'Two-handed')], help_text='empty = size table (melee/firearm/crossbow: light & medium one-handed; bows always two-handed; cloak no hand, shield/parrying dagger one hand)', null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='slot',
            field=models.CharField(choices=[('weapon1', 'Left hand'), ('weapon2', 'Right hand'), ('wings', 'Wings (one-handed only)'), ('armor', 'Armor (worn)'), ('deflection', 'Deflection item'), ('worn', 'Worn / active'), ('carried', 'Carried'), ('stored', 'Stored')], default='carried', max_length=20),
        ),
    ]
