# Generated by Django 6.0.8 on 2026-09-26 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_wings_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature request'), ('feedback', 'Feedback'), ('other', 'Other')], default='feedback', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('progress', 'In progress'), ('done', 'Done'), ('wontfix', "Won't fix")], default='new', max_length=20)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField()),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('character_name', models.CharField(blank=True, help_text='snapshot, kept if the character is deleted', max_length=120)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='characters.character')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
